folder_paths = [
  'Z:/PATH/TO/SAMPLE_FOLDER',
]

# -------- SAMPLE SETTINGS --------
sample_size = 7               # number of images per sample to select
make_zstacks = false          # create z-stacks (true/false)
z_stack_number = 5            # number of images per z-stack if enabled

# -------- OUTPUT --------
out_path = 'Z:/PATH/TO/OUTPUT_FOLDER'

# -------- ADVANCED --------
flag_custom_format = true     # true if folder format is custom
underscores_to_id = 5         # underscores before sample ID in folder name (only used if flag_custom_format=true)
