file_path = 'PATH/TO/IMAGE_FOLDER'

# -------- CHUNK SETTINGS --------

# Define the chunk size in pixels. 
# NB: The network expects a chunk size of 256. It is not recommended to use chunks below this size for training,
# as it can cause problems when applying the model to larger images.
# Larger chunks (e.g. 512) could be useful for medium to very sparse signals, but if 256 works for your signal it 
# is the safest option.

chunk_size = 256
