data_path = 'PATH/TO/CHUNKED_IMAGE_FOLDER'

# -------- FILTER SETTINGS --------

# Pixel intensity threshold. Chunks with an average intensity below this value will be filtered out.
pixel_val_threshold = 50.0

# Optional display of selected chunks in the interactive window. Slower but can be informative for evaluating the threshold.
display_selected_chunks = false

# Set to true if to get corresponding atlas chunks for your filtered chunks.
atlas_chunks_included = false
