chunk_dir = 'PATH/TO/FILTERED_IMAGE_CHUNKS'

# -------- OUTPUT --------

# Folder where selected chunks will be saved
out_dir = 'PATH/TO/SAVE_SELECTED_CHUNKS'

# -------- SELECTION SETTINGS --------

# Specify the number of chunks to select randomly
num_files_to_select = 100
